export const ERROR = "ERROR";
export const LOG_OUT = "LOG_OUT";
export const FETCH_USER = "FETCH_USER";
export const FETCH_USER_IMAGE = "FETCH_USER_IMAGE";

export const SUMMARIZE = "SUMMARIZE";
export const FETCH_SUMMARIES = "FETCH_SUMMARIES";
export const FETCH_TEAMS = "FETCH_TEAMS";
export const WAIT_FETCH = "WAIT_FETCH";
export const CANCEL_WAIT_FETCH = "CANCEL_WAIT_FETCH";
export const SHOW_NOTIFICATION = "SHOW_NOTIFICATION";
export const HIDE_NOTIFICATION = "HIDE_NOTIFICATION";
